services:
  mysql:
    image: mysql:8.4
    container_name: officeflow_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: officeflow_helpdesk
      MYSQL_USER: officeflow_user
      MYSQL_PASSWORD: officeflow_password
    ports:
      - "3307:3306"
    volumes:
      - officeflow_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./officeflow-server
      dockerfile: Dockerfile
    container_name: officeflow_api
    restart: always
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DATABASE_URL: mysql://officeflow_user:officeflow_password@mysql:3306/officeflow_helpdesk
      JWT_ACCESS_SECRET: 6112c199fa5336cd262d20c78cebab68ed25cc4ede747325d1a6c4577d53e07a
      JWT_REFRESH_SECRET: 5b719426e27f361f087a24fda2d46eaa943355305bb634a806e7228e1c594a23
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./officeflow-server/src:/app/src
      - ./officeflow-server/prisma:/app/prisma
    command: npm run dev

volumes:
  officeflow_mysql_data:
