-- AlterTable
ALTER TABLE `Notifications` MODIFY `type` ENUM(
    'TICKET_ASSIGNED',
    'TICKET_COMMENTED',
    'TICKET_STATUS_CHANGED',
    'TICKET_OVERDUE',
    'KNOWLEDGE_PUBLISHED',
    'ASSET_ASSIGNED',
    'ASSET_RETURNED',
    'LEAVE_REQUESTED',
    'LEAVE_APPROVED',
    'LEAVE_REJECTED',
    'LEAVE_CANCELLED'
) NOT NULL;

-- AlterTable
ALTER TABLE `Audit_logs` MODIFY `entity` ENUM(
    'USER',
    'DEPARTMENT',
    'TICKET',
    'KNOWLEDGE_ARTICLE',
    'ASSET',
    'LEAVE_REQUEST'
) NOT NULL;
